---
title: "Hoja 4 (a): Inferencia de una muestra con R"
author: "Departamento de Estadística e Investigación Operativa. Universidad de Sevilla"
subtitle: Estadística Computacional I. Grado en Estadística
lang: es
output:
  html_document: 
    toc: no
  pdf_document: 
    toc: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Ejercicio 1

Dibujar la densidad de la t-Student bajo H0, los cuantiles que definen los puntos críticos y el valor del estadístico


## Ejercicio 2

Dibujar un gráfico como el anterior para el contraste unilateral
para $\alpha=0.05$ y $\alpha=0.1$.

## Ejercicio 3

$$
110, 12, 2.5, 98, 1017, 540, 54, 4.3, 150, 432
$$
Se desea contrastar H0: precio medio= 500.



### Apartado a

Calcular directamente W+ (test de rango-signo de Wilcoxon)


### Apartado b

Dibujar la función de probabilidad de W+ para esta n, usando `dsignrank`.




### Apartado c 

Calcular E[W+] y Var[W+] directamente.


## Ejercicio 4

En este ejemplo se considera la hipótesis nula de que la progenie de un cruce de plantas produce como resultado plantas de tipo A o B con probabilidades respectivas 1/4 y 3/4.

En un experimento se obtienen 243 de tipo A y 682 de tipo B.

Tomando la clase B como éxito,

```
H0: p=3/4
H1: p!= 3/4
```


### Apartado a

Calcular el estadístico chi-cuadrado y comprobar que no coincide con $Z^2$.

### Apartado b

Calcular el estadístico chi-cuadrado con la corrección de Yates y comprobar que coincide con el estadístico que da prop.test.



### Apartado c

```
H0: p=0.4; 35 éxitos de 80 ensayos
```


```
H0: p=0.5; IC al 90%
```



```
H0: p=0.8; H1: p<0.8
```




